### ISSUE TITLE
command not found: apt-get

### ISSUE THREAD

**Issue by Arwa200** [turicas/nubank-to-csv#2]
Hi 

I got this error when I'm trying to run this program!

`command not found: apt-get`

![Screen Shot 2020-09-29 at 1 25 13 PM](https://user-images.githubusercontent.com/42224049/94546927-39cbcd00-0257-11eb-985b-a945e4ab6450.png)

**Comment by turicas** [comment]
This instruction was made to be run on any GNU/Linux distribution. I don't know how to install it on a Mac OS X, sorry.
